name: Build Package

# Build package on its own without additional pip install

on:
  push:
    branches:
      - main
  pull_request:

env:
  POETRY_VERSION: "1.8.3"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry env use python
      - name: Display Poetry version
        run: poetry --version
      - name: Install deps
        shell: bash
        run: poetry install
      - name: Build
        shell: bash
        run: poetry build
      - name: Test installing built package
        shell: bash
        run: python -m pip install .
      - name: Test import
        shell: bash
        working-directory: ${{ vars.RUNNER_TEMP }}
        run: python -c "import llama_index"
